/**
 * @fileoverview gRPC-Web generated client stub for greet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.14.0
// source: src/proto/greet.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_proto_greet_pb from '../../src/proto/greet_pb';


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGreet = new grpcWeb.MethodDescriptor(
    '/greet.Greeter/Greet',
    grpcWeb.MethodType.UNARY,
    src_proto_greet_pb.GreetRequest,
    src_proto_greet_pb.GreetResponse,
    (request: src_proto_greet_pb.GreetRequest) => {
      return request.serializeBinary();
    },
    src_proto_greet_pb.GreetResponse.deserializeBinary
  );

  greet(
    request: src_proto_greet_pb.GreetRequest,
    metadata: grpcWeb.Metadata | null): Promise<src_proto_greet_pb.GreetResponse>;

  greet(
    request: src_proto_greet_pb.GreetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_greet_pb.GreetResponse) => void): grpcWeb.ClientReadableStream<src_proto_greet_pb.GreetResponse>;

  greet(
    request: src_proto_greet_pb.GreetRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_greet_pb.GreetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.Greeter/Greet',
        request,
        metadata || {},
        this.methodDescriptorGreet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.Greeter/Greet',
    request,
    metadata || {},
    this.methodDescriptorGreet);
  }

  methodDescriptorGreetStream = new grpcWeb.MethodDescriptor(
    '/greet.Greeter/GreetStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    src_proto_greet_pb.Empty,
    src_proto_greet_pb.GreetResponseStream,
    (request: src_proto_greet_pb.Empty) => {
      return request.serializeBinary();
    },
    src_proto_greet_pb.GreetResponseStream.deserializeBinary
  );

  greetStream(
    request: src_proto_greet_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<src_proto_greet_pb.GreetResponseStream> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/greet.Greeter/GreetStream',
      request,
      metadata || {},
      this.methodDescriptorGreetStream);
  }

}

