/**
 * @fileoverview gRPC-Web generated client stub for history
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v0.0.0
// source: src/proto/history.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_proto_history_pb from '../../src/proto/history_pb';


export class HistorySvcClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorHistoryWinStream = new grpcWeb.MethodDescriptor(
    '/history.HistorySvc/HistoryWinStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    src_proto_history_pb.Empty,
    src_proto_history_pb.HistoryWinEventResponseStream,
    (request: src_proto_history_pb.Empty) => {
      return request.serializeBinary();
    },
    src_proto_history_pb.HistoryWinEventResponseStream.deserializeBinary
  );

  historyWinStream(
    request: src_proto_history_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<src_proto_history_pb.HistoryWinEventResponseStream> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/history.HistorySvc/HistoryWinStream',
      request,
      metadata || {},
      this.methodDescriptorHistoryWinStream);
  }

}

